### ISSUE TITLE
Angular component and mountUrl

### ISSUE THREAD

**Issue by gs-scooter** [FlatFilers/angular-adapter#9]
We are currently using an enterprise version of Flatfile, which requires our modifying the mount URL when leveraging the FlatfileImporter. I was hoping to use the Angular component, but there does not appear to be a way to specify the mount URL like you can with the importer. Is this something that can be addressed?

**Comment by brentkulwicki** [comment]
Thanks for reporting this. I'll flag this for our engineering team.

**Comment by MaksymBlank** [comment]
@gs-scooter `mountUrl` has been added to Angular component: https://github.com/FlatFilers/angular-adapter/commit/301c7f38814ef55e422f779e2b2ed8089227bb47

Closing!
